brew 'docker'
brew 'carthage'
brew 'cocoapod'
brew 'docker'
brew 'docker-machine-nfs'
brew 'git'
brew 'git-duet'
brew 'postgresql'
brew 'rbenv'
brew 'swiftlint'

cask 'istat-menus'
cask 'iterm2'
cask 'shiftit'
